services:
  - type: web
    name: sph-generator
    env: python
    buildCommand: apt-get update && apt-get install -y libreoffice libreoffice-common && pip install -r requirements.txt
    startCommand: python sph_generator.py
    plan: free
    autoDeploy: true